version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB port to the host machine
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/db:/data/db:z
    networks:
      - multiplayer-net
    command: ["mongod", "--bind_ip_all"]  # Allow MongoDB to listen on all interfaces

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis port to the host machine
    networks:
      - multiplayer-net

  multiplayer-service:
    build: .  # Build the service from the Dockerfile
    container_name: multiplayer-service
    ports:
      - "8080:8080"  # Expose HTTP API port
      - "50051:50051"  # Expose gRPC API port
    depends_on:
      - mongodb  # Ensure MongoDB starts before this service
      - redis  # Ensure Redis starts before this service
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/multiplayer_db
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=rohithk
      - REDIS_DB=0
      - SERVER_PORT=8080
      - GRPC_PORT=50051
    networks:
      - multiplayer-net
    volumes:
      - ./app.env:/app/.env:z  # Ensure volume binding works correctly on all platforms

networks:
  multiplayer-net:
    driver: bridge
